name: HTML/CSS/JS Minifier

on:
  # push:
  release:
    types: [created]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: make workspace
        run: |
          cp -vr src temp   # keep the file order
          
          echo " [i] files to minimize:"
          find temp -type f -name '*.js' -name '*.css' -name '*.html' ! -name '*.min.js' ! -name '*.min.css' ! -name '*.min.html' -ls

      - name: HTML/CSS/JS Minifier
        uses: docker://devatherock/minify-js:3.1.0  # https://github.com/devatherock/minify-js
        with:
          directory: 'temp'
          exclusions: |-
            .*min\.(js|css|html)$

      - name: merge and cleanup
        run: |
          echo " [Clear] out/*"
          rm -vr out/*
          
          echo " [Make] dev.in"
          find src -ls -fprint out/dev.in
          
          echo " [Merge] js"
          find temp -type f -name '*.min.js' -exec bash -c 'ls -l "{}"; cat "{}" >> out/main.min.js' \;
          
          echo " [Merge] css"
          find temp -type f -name '*.min.css' -exec bash -c 'ls -l "{}"; cat "{}" >> out/main.min.css' \;
          
          echo " [Copy] html"
          find temp -type f -name '*.min.html' -exec cp "{}" out/ \;
          
          ain=assets.in
          if [ -f "${ain}" ] && [ $(wc -w < "${ain}") -ne 0 ]; then
            echo " [Copy] assets (${ain})"
            cp -vr $(cat "${ain}") out/
          else
            echo " [Skip] assets (${ain})"
          fi
          
          echo " [Copy] README.rst"
          cp -v README.rst out/
          
          echo " [Make] timestamp"
          date --utc > out/timestamp
          ls -l out/timestamp
          
          echo " [Cleanup]"
          rm -vr temp

      - name: checkout
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add -A
          git commit -am "autocommit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/PythaGrids/_PythaGrid_3thParty.git
