name: HTML/CSS/JS Minifier

on:
  push:
  release:
    types: [created]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: HTML/CSS/JS Minifier
        uses: docker://devatherock/minify-js:3.1.0  # https://github.com/devatherock/minify-js
        with:
          directory: 'src'
          exclusions: |-
            .*min\.(js|css)$

      - name: make dev-index
        run: |
          find src > dev-index.txt

      - name: merge js
        run: |
          find src -type f -name '*.min.js' -ls
          find src -type f -name '*.min.js' -exec cat {} + > out/main.min.js

      - name: merge css
        run: |
          find src -type f -name '*.min.css' -ls
          find src -type f -name '*.min.css' -exec cat {} + > out/main.min.css

      - name: timestamp
        run: |
          date --utc > out/timestamp

      - name: Checkout
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add -A
          git commit -am "autocommit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/PythaGrids/_PythaGrid_3thParty.git
